#!/bin/sh -eu
#
# Outputs tab separated table in format: start end name
# Produces cut points for archive_extractor script.

journalctl --user -t nowplaying --since=-2weeks -o json |
    jq -Rr 'fromjson? | .MESSAGE |= fromjson | [(.__REALTIME_TIMESTAMP | tonumber / 1e6 | floor), .MESSAGE.show // "-", .MESSAGE.artist // "-", .MESSAGE.title // "-"] | @tsv' | {
    ts_start=
    title=
    old_show=-
    while IFS='	' read ts_end new_show new_artist new_title; do
	#echo $ts_end
	#echo $new_show
	#echo $new_artist
	#echo $new_title
	#echo ---
	if test "$title" -a '(' "$new_show" = - -o "$new_artist" = - ')'; then
	    # End of previous show
	    echo "`date -Isec -d @$ts_start`\t`date -Isec -d @$ts_end`\t$title"
	    title=
	fi

	if test "$new_show" != - -a '(' "$new_artist" = - -o "$old_show" = - ')'; then
	    # Start of a new show
	    ts_start=$ts_end
	    if test -z "$new_artist"; then
		title="$new_show"
	    else
		title="$new_show: $new_title"
	    fi
	fi

	old_show="$new_show"
    done
}
